# Generated by Django 4.2.2 on 2023-06-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=25)),
                ('discount', models.CharField(max_length=10)),
                ('second_price', models.CharField(max_length=10)),
                ('pic', models.CharField(max_length=255)),
            ],
        ),
    ]
