# Generated by Django 4.2.2 on 2023-07-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pant_sock_rename_product_clothe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clothe',
            new_name='Tshirt',
        ),
    ]
